/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.6/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {

//    include plugin for manual testing
//    See: https://docs.gradle.org/current/userguide/testing_gradle_plugins.html
    includeBuild("../my-git-plugin")

    plugins {
//        id("org.example.openapi-gradle-plugin") version "0.0.1"
//        id("openapi-plugin") version "0.0.14"
        id("org.openapi.generator") version "7.5.0"
    }

    repositories {
        mavenLocal()
        gradlePluginPortal()
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
//    id("org.example.openapi-gradle-plugin")
}

rootProject.name = "gradle-simple-app"
include("app")
