/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println("do not add to commit")
    println(App().greeting)

    println("add to commit 1")
    println("add to commit 2")
}
